### ISSUE TITLE
AT Command is not working with SDK

### ISSUE THREAD

**Issue by ioteng** [Ai-Thinker-Open/GPRS-AT#2]
Hi, I am using a9G pudding board and using "Ai-Thinker_A9_firmware_release_v1.6_RC" firmware. 
With native firmaware i can use AT commands with no problem. 
I uploaded demo gpio app according to instructions  "https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/burn-debug.html" then i can not use serial port and AT commands. 
My question isn't it possible to use AT commands on an app uploaded board.

**Comment by Neutree** [comment]
C SDK not contain any AT code

**Comment by ioteng** [comment]
I know SDK is not contain AT code; I only want to use AT commands on serial on SDK app uploaded board. 
is it possible?
