### ISSUE TITLE
unable to upgrade A9G firmware on windows 7

### ISSUE THREAD

**Issue by kesmtk** [Ai-Thinker-Open/GPRS-AT#5]
Hello I have A9G module with 2018 06 firmware,
I have usb to serial (3.2 volt logic)adapter but fpupgrade.exe does not recognize module, nothing to select in the list of com ports .
![upgrade](https://user-images.githubusercontent.com/45457917/49223326-618d4800-f3d6-11e8-9c92-84a256e63fc0.png)

Here is what I get on comport on host uart when I boot up device
![host rx](https://user-images.githubusercontent.com/45457917/49223170-e9268700-f3d5-11e8-804e-c9fc40dd5ad0.png)

**Comment by ppsaheed** [comment]
https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/hardware/usb-uart-module.html

**Comment by kesmtk** [comment]
I used OTI006858
I found photo on google
http://electron55.ru/images/stories/site/misc/usb-com/DSCN1285-800.jpg

**Comment by kesmtk** [comment]
upgrade success with CP2102
